# Generated by Django 3.2.4 on 2021-07-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sample',
        ),
    ]
